---
title: "Project Proposal"
author: "The Four-mula: Hellen Han, Lila Rogers, Amy Duan, Eva Aggarwal"
format: pdf
execute: 
  warning: false
  message: false
editor: visual
---

```{r}
#| label: load-pkg-data
library(tidyverse)
library(tidymodels)
# add other packages as needed

# add code to load data
```

## Introduction

-   An introduction to the subject matter you’re investigating (citing any relevant literature)

-   Statement of a well-developed research question.

-   The motivation for your research question and why it is important

-   Your team’s hypotheses regarding the research question

    -   This is a narrative about what you think regarding the research question, not formal statistical hypotheses.Data description

## Exploratory data analysis

-   The source of the data set

-   A description of when and how the data were originally collected (by the original data curator, not necessarily how you found the data)

-   A description of the observations and general characteristics being measured

## Analysis approach

-   Description of data processing you need to do to prepare for analysis, such as joining multiple data sets, handling missing data, etc.

-   Visualizations, summary statistics, and narrative to describe the distribution of the [**response**]{.underline} variable.

## Data dictionary

The data dictionary can be found [here](ADD%20LINK!!!) \[Update the link and remove this note!\]
