---
title: "Research Topics"
author: "The Four-mula: Hellen Han, Lila Rogers, Amy Duan, Eva Aggarwal"
format: pdf
execute: 
  warning: false
  message: false
editor: visual
---

## Research Topic 1: AI-powered job market insights

One topic that captured our interest was the potential impact of Artificial Intelligence on the Job market. We all share an interest in Artificial Intelligence and its growing impact on our world, and are curious about how its influence may impact the economy and job market. People interested in this data set could be people entering the work force (us), or employers looking to optimize strategy.

**Potential Research Questions:**

1.  What factors influence an industry’s likelihood of adopting AI technologies?

2.  Which job roles are at the highest risk of automation, and how does this risk vary by industry/salary?

3.  How can we quantify the risk associated with certain jobs?

We have some potential datasets that we are considering using at this time:

1.  AI Job Market Unveiled: Insights from 500 Data Points on Roles, Skills, and Salaries \[<https://www.gigasheet.com/sample-data/ai-job-market-insights>\]
2.  AI-Powered Job Market Insights a synthetic but realistic snapshot of the modern job market on the role of AI \[https://www.kaggle.com/datasets/uom190346a/ai-powered-job-market-insights\]

\pagebreak

## Research Topic 2: **A** Characteristic Analysis of Aviation Accident

With several aviation accidents happening in recent periods, it is interesting to look into the historical aviation accident database, in terms of what majorly caused aviation accidents in order to better avoid similar incidents from happening in the future. We believe potential audiences include the general public who take flights to travel in both personal and business forms; people interested in airplane manufacturing industries in terms of how to minimize aviation accidents in manufacturing.

Potential research questions for the following topic include: 

1. What are the most common causes of aviation accidents historically, and how have they changed over time?

2. What role do human factors and environmental factors play in aviation accidents compared to mechanical or environmental causes?

3. What characteristics of aircrafts have the largest percentage in causing accidents?

Potential datasets we can use are aviation accident databases, such as historical databases like the National Transportation Safety Board (NTSB) aviation accident database and Aviation Safety Network. These databases typically include details on accidents, including dates, locations, causes, and severity (fatal/non-fatal). Furthermore, we can analyze global accident trends, such as aggregated reports from organizations like the International Civil Aviation Organization (ICAO) or Boeing’s Statistical Summary of Commercial Jet Airplane Accidents.

\pagebreak

## Research Topic 3 : **Fitness, Lifestyle, and Health Analysis**

The following topic seeks to explore the impact of lifestyle factors on various health metrics and fitness levels, uncovering how different factors (exercise, sleep, stress levels, etc.) impact overall health and fitness outcomes. Our motivation for investigating this topic is to conduct health analytics, confirming the existing knowledge of fitness levels and lifestyle factors on health metrics while identifying early warning signs of health issues. Understanding the relationship between fitness activity, lifestyle choices, and health indicators is crucial for promoting healthier habits and predicting risk of health conditions. The potential audiences of the following analysis would be healthcare professionals, the general population, and fitness trainers and wellness coaches interested in using data-driven insights to understanding how lifestyle factors and fitness influence health to strengthen recommendations and next courses of action. 

Potential research questions for the following topic include: 

1. What fitness activities and lifestyle choices most positively influence health metrics?

2. How do various lifestyle choices impact overall fitness levels? 

3. Which demographic factors influence the effectiveness of various activity types on blood pressure? 

Potential data sets we're interested in using involve basic demographic information about an individual, their activity and lifestyle choices, as well as various health indicators/disease prevalence. A potential dataset that we are considering is: \[<https://www.kaggle.com/datasets/jijagallery/fitlife-health-and-fitness-tracking-dataset>\], which provides a comprehensive view of individuals' daily activities, health metrics, and lifestyle habits. 


