---
title: "Analysis of IMDb Movie Revenue"
author: "The Four-mula: Hellen Han, Lila Rogers, Amy Duan, Eva Aggarwal"
date: "3/20/2025"
format: pdf
execute: 
  warning: false
  message: false
  echo: false
editor: visual
---

## Introduction 



```{r}
#| label: load packages and data

library(tidyverse)
library(tidymodels)

imdb_data <- read_csv("data/Imdb Movie New Data_v2.csv")
```

```{r}
imdb_data_cleaned <- imdb_data %>% 
  filter(revenue > 0) %>% 
  mutate(log_revenue = log(revenue)) 
summary(imdb_data_cleaned$log_revenue)
```

```{r}
imdb_data_cleaned %>% 
  ggplot(mapping = aes(x = log_revenue)) + 
  geom_histogram() + 
  labs(title = "Distribution of Log-Transformed IMDb Movie Revenue", 
       x = "Total Log Transformed Revenue (USD)", 
       y = "Count") + 
  theme(plot.title = element_text(size = 10))
```

Your written report goes here!

::: callout-important
Before you submit, make sure your code chunks are turned off with `echo: false` and there are no warnings or messages with `warning: false` and `message: false` in the YAML.
:::
